<a href="https://colab.research.google.com/github/rohinikhanderay/Numpy-Tutorial/blob/main/Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy package is referred as np

In [ ]:
import numpy as np

In [ ]:
ar=np.array([27,24,100,25])

In [ ]:
print(ar)

[ 27  24 100  25]


In [ ]:
print(type(ar))

<class 'numpy.ndarray'>


# create 0s and 1s matrix

In [ ]:
np.ones(5)             # 1s array is bydefault float type

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))  # create 1s matrix of 3 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# convert data type of array

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
x=np.zeros(6,dtype=str)

In [ ]:
x                  # we get empty string '' which is zero

array(['', '', '', '', '', ''], dtype='<U1')

In [ ]:
x=np.zeros(6,dtype=bool)

In [ ]:
x               # false represent 0 value

array([False, False, False, False, False, False])

# create Empty matrix

In [ ]:
np.empty((2,4))             #it consist random or garbage values

array([[4.66181840e-310, 1.58101007e-322, 6.77127876e-043,
        1.40415966e+165],
       [5.64529821e-062, 2.19291210e-076, 3.69784498e-057,
        3.91080547e-315]])

# Dimensions in array (0-D array)

In [ ]:
import numpy as np

In [ ]:
arr=np.array(45)

In [ ]:
print(arr)

45


# 1- D array

In [ ]:
import numpy as np

In [ ]:
arr_1d=np.array([27,24,100,25])

In [ ]:
print(arr_1d)

[ 27  24 100  25]


# 2D array

In [ ]:
import numpy as np

In [ ]:
arr_2d=np.array([[100,24],
            [78,9]])

In [ ]:
print(arr_2d)

[[100  24]
 [ 78   9]]


# 3D array

In [ ]:
import numpy as np

In [ ]:
arr_3d=np.array([[[100,24],
            [78,9]],[[26,78],[11,10]]])

In [ ]:
print(arr_3d)

[[[100  24]
  [ 78   9]]

 [[ 26  78]
  [ 11  10]]]


In [ ]:
print(arr_3d.ndim)         #To check dimensions of array
print(arr_3d[0,1])          # access elements in 3D array

3
[78  9]


In [ ]:
# Solve???
#arr = np.---([56,19,58,11,98])     fill in the blanks ---

# Access array elements

In [ ]:
import numpy as np

In [ ]:
arr=([19,23,56,89])

In [ ]:
print(arr[2])                  #acess elements by writting index number
print(arr[2]+arr[0])           # concatenate 2 elements in array

56
75


In [ ]:
print(arr[2]+arr[0]) 

75


In [ ]:
# Solve???
# Insert the correct syntax for printing the first item in the array.
# arr = np.array([1, 2, 3, 4, 5])


# access 3D array

Ex. Access the third element of the second array of the first array:

In [ ]:
import numpy as np

In [ ]:
a=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
print(a[0,1,2])

6


Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

# Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Note: The result includes the start index, but excludes the end index.

In [ ]:
import numpy as np

In [ ]:
arrx = np.arange(1,101).reshape(10,10)
arrx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
arrx[0]           #it will slice row 0,all hori values & it is 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arrx[: , 1]       #it shows all values from column 1  & it is 1D (all row so write :)

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [ ]:
arrx[:, 1:3]      # acess colum num 1and 2 and all row so write (:)

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [ ]:
arrx[0:4, 1:3]             # you can access particular row and column

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33]])

# STEP
Use the step value to determine the step of the slicing. 
We can also define the step, like this: [start:end:step].

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


# Negative Slicing
Example
Slice from the index 3 from the end to index 1 from the end:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(arr[-3:-1])


[4 5]


# Numpy functions

In [ ]:
import numpy as np

# **arange**

In [ ]:
# np.arange(start,end,step)
a=np.arange(2,20)
print(a)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#if we want only even numbers in array, then we need to give step
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


# ***Linespace***

In [ ]:
# in linespace we are giving a range of values.i.e. how many values we want within that range. here 1 is start 10 is end and within this range we want 7 values
x=np.linspace(1,10,7)
print(x)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


# **ravel**

In [ ]:
#It again convert 2D or 3D into 1D array
arr.ravel()

array([1, 2, 3, 4, 5, 6])

# **reshape**

In [ ]:
# here we convert 1 D array in 2D
# above arr 1 D array having 6 elements. as we conver into 2D then write (2,3) 2rows and 3 columns
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# **transpose**

In [ ]:
# it convert rows into columns

In [ ]:
ar=np.array([[27,24,100,25],[1,5,6,9]])
ar.T

array([[ 27,   1],
       [ 24,   5],
       [100,   6],
       [ 25,   9]])

# **NumPy Array Copy vs View**
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
# copy

In [ ]:
import numpy as np

In [ ]:
arr=np.array([23,13,56,89])

In [ ]:
a=arr.copy()

In [ ]:
print(a)

[23 13 56 89]


In [ ]:
a[0]=45

In [ ]:
print(a)
print(arr)

[45 13 56 89]
[23 13 56 89]


In [ ]:
# View

In [ ]:
import numpy as np

In [ ]:
arr=np.array([23,78,11,89])

In [ ]:
x=arr.view()

In [ ]:
arr[0]=99

In [ ]:
print(x)

[99 78 11 89]


In [ ]:
print(arr)

[99 78 11 89]


# **Joining or concatenate NumPy Arrays**

In [ ]:
import numpy as np

x1 = np.array([1, 2, 3])

x2 = np.array([4, 5, 6])

arr = np.concatenate((x1, x2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
np.vstack((x1,x2))               #arrange array vertically i. e column form

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((x1,x2))               #arrange array horizontally i. e row form

array([1, 2, 3, 4, 5, 6])

# **Splitting NumPy Arrays**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# **Searching Arrays**

In [ ]:
import numpy as np

In [ ]:
arr=np.array([12,45,67,89,12,13,12,12])

In [ ]:
x=np.where(arr==12)

In [ ]:
x

(array([0, 4, 6, 7]),)

In [ ]:
arr.ndim             # check for array dimension


1

In [ ]:
arr.size             # check for array size (it is number of elements or numbers in array.)

8

In [ ]:
# Check for shape i. e. how many rows and columns

In [ ]:
arr1=np.array([[100,24],
            [78,9]])

In [ ]:
arr1.shape
arr1.dtype    # Check for data type store in array. its integer of capacity 32 bits

dtype('int64')

# **Mathematical calculation using numpy**

In [ ]:
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(11,20).reshape(3,3)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
a1+a2             # both array get added

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
np.add(a1,a2)     # other way to add array by add function

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
np.subtract(a1,a2)       # subtraction

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [ ]:
np.divide(a1,a2)          #divide

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [ ]:
np.multiply(a1,a2)         # multiply

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

# **find max value in array**

In [ ]:
a1.max()

9

In [ ]:
a1.max(axis=0)        #max values of each column

array([7, 8, 9])

In [ ]:
a1.max(axis=1)         # max value of each row

array([3, 6, 9])

# **find min value in array**

In [ ]:
a1.min()

1

In [ ]:
a1.min(axis=0)

array([1, 2, 3])

In [ ]:
a1.min(axis=1)

array([1, 4, 7])

In [ ]:
np.sum(a1)             # sum of all elements from array1

45

In [ ]:
np.sum(a1,axis=0)       # sum of each column and axis=0 represent columns

array([12, 15, 18])

In [ ]:
np.mean(a1)              #avrg of array

5.0

# **Random Sampling**
To generate random numbers like OTP

In [ ]:
np.sin(180)

-0.8011526357338304

In [ ]:
import numpy as np

import random

In [ ]:
np.random.random([3,4])          #generate random array

array([[0.85062631, 0.46245793, 0.3902129 , 0.6222627 ],
       [0.39594357, 0.27387356, 0.57450382, 0.40975502],
       [0.04639213, 0.72750416, 0.50038599, 0.08221918]])

In [ ]:
np.random.randint(1,9)             #generate random number between range 1 to 9,include 1 and exclude 9

7

In [ ]:
np.random.randint(1,4,(4,4))      #creatre 4x4 matrix of random variable of range between 1 and 4

array([[3, 1, 3, 1],
       [1, 2, 3, 2],
       [2, 2, 2, 2],
       [2, 1, 3, 2]])

In [ ]:
x=[3,6,7,9,12,67,89,11]           # choice will select random num from the list

In [ ]:
np.random.choice(x)

67

In [ ]:
np.random.shuffle(x)              #shuffle items from list x
print(x)

[12, 89, 11, 3, 67, 6, 7, 9]


# **String Operation using NumPy**

# New Section

# New Section

In [ ]:
name1="hello Students"
name2=" WELCOME to the machine learning series"
np.char.add(name1,name2)                          #strings can be add using char.add function

array('hello Students Welcome to the machine learning series',
      dtype='<U53')

In [ ]:
np.char.lower(name2)                #lower case

array(' welcome to the machine learning series', dtype='<U39')

In [ ]:
np.char.upper(name1)

array('HELLO STUDENTS', dtype='<U14')

In [ ]:
np.char.center(name1,50)          #string appeared in center and 50 is length of string(it can b anything)

array('                  hello Students                  ', dtype='<U50')

In [ ]:
np.char.center(name1,90,fillchar="*")           #center filled with *** 

array('**************************************hello Students**************************************',
      dtype='<U90')

In [ ]:
np.char.split(name2) # strings splitted in the form of list variables

array(list(['Welcome', 'to', 'the', 'machine', 'learning', 'series']),
      dtype=object)

In [ ]:
np.char.splitlines("hello\nhow are you")

array(list(['hello', 'how are you']), dtype=object)

In [ ]:
np.char.replace(name1,"hello","Good morning") # replace old string with new one.hello is replace by good morning

array('Good morning Students', dtype='<U21')

In [ ]:
np.char.equal(name1,name2)

array(False)

In [ ]:
np.char.count(name1,"l") # it counts no of times char present in string

array(2)

In [ ]:
np.char.find(name1,"e")   #find location of character from string 

array(1)